
Adam Smith was arguably the first great Enlightenment thinker to offer a thorough
and considered response to the writings of Jean-Jacques Rousseau, the first great
Counter-Enlightenment thinker. As recent scholarship has stressed, Smith sympathized
with many aspects of Rousseau’s wide-ranging critique of commercial society. In the end,
however, their differences were far more fundamental. This essay examines four key areas
of divergence between the two, namely their views on the popular dissemination of
the arts and sciences (and popular ‘enlightenment’ more generally); the moral effects
of commerce; the nature of liberty and citizenship; and the idea of progress. In each case,
Smith stood closer to the leading figures of the French Enlightenment—thinkers such as
Montesquieu, Voltaire, and Diderot—than he did to their great critic Rousseau.


----------

Charles L. Griswold
Jean-Jacques Rousseau and Adam Smith: A Philosophical Encounter

Charles L. Griswold, Jean-Jacques Rousseau and Adam Smith: A Philosophical Encounter, Routledge, 2018, 275pp., $95.00, ISBN 9781138218956.

Reviewed by James R. Otteson, Wake Forest University

This is a sophisticated, complex book. Those familiar with Griswold's earlier work -- for example, his Adam Smith and the Virtues of Enlightenment (1999) or his Forgiveness: A Philosophical Exploration (2007) -- will have come to expect the combination of close reading of primary texts, vast familiarity with secondary literature, and subtle and careful reasoning that is on display in this book. It is not suitable for general audiences or for readers looking for overviews or summaries of Rousseau or Smith, however: it requires focused attention, and without wide background familiarity with Rousseau's and Smith's works, much of its discussion may be difficult to follow and evaluate. For readers with the requisite expertise and time to devote to it, however, Griswold's book repays close investigation. Like his other works, its exegesis and argument are subtle, detailed, and careful; and, again like Griswold's other work, it will immediately become a reference that will shape future scholarship.

The book's opening discussion sets the frame for most of what follows. Griswold calls our attention to the fact that Rousseau attached a Preface to his play Narcissus. This fact might initially not seem remarkable -- until one reads the Preface, which, as Griswold shows, defends the "critique of the arts, letters, sciences, and philosophy" (3) that Rousseau presented in his First Discourse. In other words, Rousseau offers a sharp criticism of arts and letters in his Preface, and then publishes it together with Narcissus in which he engages in and contributes to arts and letters. How can we reconcile this seeming contradiction between Rousseau's words (Preface) and his deeds (writing and publishing Narcissus)? After careful discussion, Griswold concludes that Rousseau is indeed "guilty as charged" of inconsistency between his words and deeds (17). But that is not the end of the story, because, as Griswold argues, for Rousseau there is no way to extricate ourselves from the "system of falsification, rationalization, and ambitious performance" that modern society requires (17). Thus, there is a kind of wisdom in Rousseau's juxtaposition of his Preface with his Narcissus: like Socrates claiming that the realization that he knew nothing was itself the basis of his wisdom, Rousseau's realization that we are all performing roles, and that these roles are partly both self-constructed and self-deceiving, is the beginning of a kind of self-knowledge even if "we don't know how to live without our fictions" (18).

A larger question with which Griswold's examination is concerned is the degree to which modern commercial society exacerbates the mutual self-deception in which we engage. Can commercial society offer any redeeming virtue through the multiple layers of deception and self-deception it encourages? One way to approach this question is to consider Adam Smith's claim, in his Wealth of Nations, that "It is not from the benevolence of the butcher, the brewer, or the baker, that we expect our dinner, but from their regard to their own interest. We address ourselves, not to their humanity but to their self-love, and never talk to them of our own necessities but of their advantages" (Wealth of Nations I.ii.2). However straightforward this passage seems at first blush, it actually raises a host of questions. First is whether Smith is here making a descriptive or a normative statement; is he describing the way people in fact operate in markets, or is he recommending that we behave in this way? If the former, the claim seems false: we often do consider benevolent motives and actions when we interact in markets, particularly in local, small-town markets like what Smith seems to be describing, where we often know our butcher, brewer, or baker personally. If the latter, then Smith owes us an argument about why we should put aside what seem to be our natural affections when we enter the marketplace.

Beyond that question, however, is one that is of more concern to Griswold: to what extent are our interactions and exchanges in the marketplace between, in fact, constructed and projected artificial selves, as opposed to expressions of authentic selves? If I appeal to your interest, do I actually care about your interest, or is this mere posturing? If you similarly posture, then surely you know that I too am posturing -- as I know you are. So how can our interaction be anything approximating entering into genuine community with one another, when each of us is not only posturing but knows the other is posturing -- and yet we proceed as if we are not posturing and as if we do not know that each of us is?

Thinking through an example like this gives some sense of the philosophical and exegetical complexities involved with putting figures like Rousseau and Smith in conversation with one another. But Griswold is clearly up to the task. Though he confesses that he is "a philosopher, not a historian (including a historian of ideas)" (xx), and he intimates that there is too much secondary scholarship on Rousseau and Smith for him to have mastered completely (xix), nevertheless he has an uncommon command of both the primary and relevant secondary literature that surpasses most scholars of those figures. This fact at times makes working through his discussions, including his voluminous footnotes, tough slogging, but it also gives the reader confidence that if there is a text, passage, or reference that is relevant, Griswold has found it.

There are far too many insightful discussions to cover in a review, but one discussion will give some sense of other parts of its content. Adam Smith famously identified a personage he called the "impartial spectator" as the standard of moral behavior. In practice, the impartial spectator serves as a heuristic device: If you wonder whether what you are contemplating doing is moral or not, ask yourself what a disinterested but fully informed observer of your conduct would think. Would such a person approve? Smith apparently believes that asking oneself this question can give one reliable advice, but questions arise regarding the origin of this perspective. Smith argues that the perspective arises from a process of induction in which individuals engage over their experiences of observing how others judge others' and one's own behaviors, sentiments, and judgments. The thousands of such experiences one has had lead one to develop judgment about what is acceptable or unacceptable in human conduct -- and this judgment is generated by asking ourselves whether an impartial spectator would approve. Yet if that is the origin of this perspective, it would seem necessarily tied to the particular experiences each individual has had. In that case, what would prevent it from being parochial and subject to the biases, prejudices, and chauvinisms native to one's local community or one's peculiar experiences? Why should we consider the impartial spectator's perspective anything more than the coalescence of localized tribalisms -- and the recommendation to follow it therefore little more than the recommendation to follow locally contingent strategies to get along in one's community, and not any kind of objective moral code?

The process of asking what an impartial spectator would think of one's conduct necessarily involves a process of imaginative projection. As Smith says:

When I endeavour to examine my own conduct, when I endeavour to pass sentence upon it, and either to approve or condemn it, it is evident that, in all such cases, I divide myself, as it were into two persons; and that I, the examiner and judge, represent a different character from that other I, the person whose conduct is examined into and judged of. (Theory of Moral Sentiments III.1.6)

As Griswold points out, this puts us squarely back into Rousseau's problematic: the two persons into which I divide myself are in imagination only, subject to the self-delusions and lack of self-knowledge Rousseau argues each of us has; and, of course, it is still I who is doing the 'dividing,' 'imagining,' and judging. Smith seems to think that consulting the perspective of the impartial spectator can give us some critical distance from ourselves, some outside perspective and context from which to judge ourselves that can lend our judgment objectivity. But Rousseau questions not only whether an imaginary impartial spectator's perspective can be objective, but indeed whether such critical distance is even possible. If we are so opaque to ourselves, how much trust can we place in an imaginary perspective that it is at one step further remove from ourselves? Summarizing the Rousseauian position, Griswold writes that

the empirical evidence as well as intuitions to which we would normally appeal in setting out our view of human nature are already historically and conceptually mediated. The effort to know ourselves reinforces those inherited and culturally shaped biases precisely by pretending that they constitute objective, impartially known facts or theses. (51)

This would not enable objectivity, however, but merely compound the opacity, self-ignorance, and mutual deception.

As Griswold argues, one central, unifying theme of much of Rousseau's work is an exploration of -- or perhaps performative illustration of -- "the theme of self-knowledge and pervasive lack of clarity about oneself" (59). We imagine ourselves as unified selves with fairly stable characters and personalities; yet we in fact have little idea about ourselves at all, and hence our expressions of behavior, sentiments, and judgments are poses we adopt. In a perhaps surprising way, this is both a confirmation and condemnation of the Smithian perspective. We adopt postures that allow us to move, and even succeed, in the social circumstances in which we find ourselves, and we construct an artificial standard of morality -- the "impartial spectator" -- which we hold out to others as, and even convince ourselves of being, objective. But it is in fact merely a product of our search for stratagems to make us feel better about ourselves and to make others approve of our conduct (144). Hence Smith's claim that all human beings desire "mutual sympathy of sentiments" becomes not the positive social force Smith imagines, but instead a mutually corrupting device for securing praise and flattery that itself constitutes yet a further obstacle to self-knowledge (148). Thus, when Smith claims that we naturally desire not only praise but to be praiseworthy -- "Man naturally desires, not only to be loved, but to be lovely; or to be that thing which is the natural and proper object of love" (TMS III.ii.1) -- the Rousseauian understands that as not only a false pretense, but, when it is deployed (as it inevitably will be), as a post-hoc rationalization for one's behavior, an exercise in self-flattery to boot.

One commonality between Smith and Rousseau that Griswold discusses at length is their shared methodology of looking to the past -- to "genealogical narratives" -- to understand why people behave, and why they judge, the way they do. Both of them believe that our current selves, including our moral sentiments, arise from a complex interaction between us and others in our experience, between us and our culture, and, in a way that is unfortunately forever opaque to us, between us and our various selves that we project to different people in different situations. As Griswold rightly points out, "Smith's outlook is not as pessimistic as" Rousseau's (92), and Griswold gives some reason to support Smith's more optimistic claim that, despite the difficulties involved with generating true community with others, nevertheless Smith "is asserting that we do have experience of 'what other men feel,' that we regularly do consider or share or see or feel their sentiments and motives, and that when we are incapable (if the other person is dead, for example) we can still imagine what that person would feel" (119). According to Griswold, Rousseau's claim that "sociability is artificial" (107) does not prove that "once we understand the situation [of others] we cannot enter into their sentiments" (120). Smith writes: "These two sentiments [those of an actor and of an observer to the actor's conduct], however, may, it is evident, have such a correspondence with one another, as is sufficient for the harmony of society. Though they will never be unisons, they may be concords, and this is all that is wanted or required" (TMS I.i.4.7). As Griswold points out, this is the basis of Smith's relative optimism that, our lack of self-knowledge notwithstanding, our social orders can be beneficial: "Smith's picture of the proclivity of the imagination helps to underwrite the connection between ground-level sociability and prosocial sentiments and conduct" (126).

I wonder, however, whether Rousseau's critique might not have more power than Griswold seems to allow. Note that Griswold argues that Rousseau's claims about the artificiality of sociability do not prevent us from entering into others' sentiments "once we understand the situation" of those others: but a central part of Rousseau's argument questions whether we can, in fact, understand the situation of others. Rousseau's argument does not hang on the claim that we are not in fact other people, that we do not occupy their bodies or view them from within them, as it were (122). Rather, it makes the deeper claims that (a) there is no unified, authentic self in others to know -- there are only their multiple constructed and shifting selves -- and (b) the same is true for us as well, which means we have no stable or core or authentic self from which to view others. Hence, while it may be true that "the human self naturally gravitates to norms by which it can, by adopting the spectatorial standpoint made possible by the sympathetic imagination, measure itself" (128), there is little reason to trust either these standards of measurement or the process that produced them. Griswold argues: "A narrative understanding of a person's situation does not, simply because it is narrative, reduce understanding to confabulating" (142). Fair enough, but presumably Rousseau would respond that neither does it give us reason to believe it is anything other than confabulating. Griswold: "If local knowledge is corruptible in the ways Smith himself concedes, then (Rousseau would likely infer) it is not to be trusted" (148). Just so; but does this not undermine Smith's argument? Griswold continues: "Smith could claim that a degree of objectivity and impartiality is available to the theorist, but from a standpoint avowedly rooted in 'common life,' and that he has avoided the difficulties that accompany Rousseau's starkly dyadic outlook" (148). But Rousseau would likely argue that the concession "from a standpoint avowedly rooted in 'common life'" gives the game away.

Griswold goes on to explore several other fascinating implications of the imagined philosophical "encounter" between Smith and Rousseau, including their endorsement and criticism, respectively, of commercial society (chapter 4), and their differing views of the place and value of "civil religion" in society (chapter 5). Griswold's examination throughout is careful, insightful, and provocative. I cannot do justice to his treatment in a review, unfortunately, but I hope the above discussion of other aspects of Griswold's book make it clear that Rousseau scholars, Smith scholars, and anyone else interested in how these two great thinkers explored "questions of the self" (248) will find his discussion enormously fruitful.


