
==== [.black]#Humanistic Practices 2016-2017#

Since 1990 I have refined my methodology to 9 core practices have evolved from an innovative technology
focus to embracing a collaborative culture that encourages creativity over process. In the past these
practices incorporated Enterprise Architecture, Agile and Design Patterns. Over the course of my career
a key enabler has been the hands on experience and teaching on how to derive benefits with each practice at
University of North Texas, Wisconsin, California, XCare, DMR, Williams, NorTel and Glaxo. I current working to
extend Humanistic Practices to Data Science, Knowledge and Wisdom.
See: link:https://speakerdeck.com/axiom6/humanistic-practices[Humanistic Practices]

[width=50%,cols="10,15,15,15",options="header"]
|====
^|         ^| Embrace     ^| Innovate   ^| Encourage
 | *Learn* ^| Collaborate ^| Product    ^| Discovery
 | *Do*    ^| Adapt       ^| Technology ^| Benefits
 | *Share* ^| Change      ^| Production ^| Govern
|====

[cols="15,85",frame="none",grid="none"]
|====
| Collaborate | Team building with psychological safety for creative interaction
| Product     | Transforming value propositions into an attractive portfolio
| Discovery   | Finding and sharing our vision within our company and to our clients
| Adapt       | Tracing features, components and acceptance to fine tune our efforts
| Technology  | Innovative 4 tier architecture, engineering and construction
| Benefit     | Realizing the benefits that propel our discoveries
| Change      | Continuous delivery leading to evolutionary architecture
| Production  | Sharing our work with our client communities on the cloud
| Govern      | Inspiring resources to improve the maturity of our communities
|====


