
==== [.black]#GIS# [.black .right]#Criterion&#160;&#160;&#160;&#160;&#160;&#160;&#160;1987-1990#

Designed and built LandTrak Plus, a complete Geographic Information System (GIS) for the telephone industry. In
its time LandTrak was a major competitor in the PC GIS market with MapInfo and ESRI. LandTrak mapped street
networks (Census Dime Files) for public safety and education. LandTrak Plus added an event driven GUI
framework and persistent classes to dynamically query thematic data associated with graphically depicted map
features. These capabilities enabled cable-transfer and loop-makeup that traversed telephone cable pair hierarchies.
Prototyped a network topology for the connectivity and associatively of map features.

==== [.black]#Reengineering# [.black .right]#Telcor&#160;&#160;&#160;&#160;&#160;&#160;&#160;1985-1987#

Provided technical expertise to telephony experts who were tasked with reengineering the drawing and record
management processes for outside plant and central office telephone networks. Wrote specifications for an
integrated facility management system that combined CAD, GIS, and databases to manage assets of 14.5 billion
dollars. During the study period my team gathered user requirements and interviewed over 30 CAD and GIS
vendors. Coordinated a field trial with ESRI to demonstrate ARC / INFO’s outside plant capabilities. Defined a
design methodology that combined entity-relationship, state-transition and data flow diagrams.

==== [.black]#CAD# [.black .right]#UniCad&#160;&#160;&#160;&#160;&#160;&#160;&#160;1984-1985#

Worked with a start-up company on the design and programming of a CAD toolbox in C. The main product was
called MPE for Modifiable, Portable and Extensible software. MPE consisted of subsystems for drafting, solid
modeling (Romulus), customizable user interfaces (UIMS), device independent graphics (GKS), a relational
database (Oracle), and a structured application language (SAL). My contributed 3D geometry, modeling and GKS.

==== [.black]#Geology# [.black .right]#Petroleum Information&#160;&#160;&#160;&#160;&#160;&#160;&#160;1980-1984#

My team at Petroleum Information designed GAS (Geologic Analysis System) with integrated graphics, data base, and statistics. GAS was
the culmination of over four years of data collection, programming and analysis on Alaska's North Slope.
These projects were researched, designed and coded in close collaboration with scientists at the USGS.

[cols="12,88"]
|====
| SDS      | A complete multivariate statistics package with curve fitting, spreadsheet, data retrieval and graphics.
| TECHSYS  | An entire database system for oil well and production data.
| DEMS     | A digitized mapping system for oil well location and USGS DLG (Digital Line Graph) file formats.
| TTI      | An oil maturation and burial history package.
| SRG      | Markov Chains for modeling sedimentary transitions.
| SEDAS    | An earthquake recognition and location system in UNIX with the USGS branch of Global Seismology.
|====

<<<<

==== [.black]#Geophysics# [.black .right]#Texas Intruments&#160;&#160;&#160;&#160;&#160;&#160;&#160;1978-1980#

At Texas Instruments I programmed wavelet-processing modules that utilized Fourier (frequency) and Hilbert (phase) transforms that
sharpened fuzzy minimum phase wavelets to symmetric zero phase wavelets. Additional wavelet modules filtered
marine air gun bubbles and reconstructed Vibroseis frequency sweeps. Designed a complete grid and contour
system with geologic fault honoring.

==== [.black]#Math Instructor# [.black .right]#Arapahoe Community&#160;&#160;&#160;&#160;&#160;&#160;&#160;1974-1978#

At Arapahoe Community College  I taught and developed course materials for 17 math courses from arithmetic up through calculus
and differential equations. Administered teacher training, authorized course changes, supervised registration, and
assisted in career counseling.

==== [.black]#Academics# [.black .right]#Colorado School of Mines&#160;&#160;&#160;&#160;&#160;&#160;&#160;1973-1978#

Mathematics courses: Differential Equations, Partial Differential Equations, Numerical Analysis, Integral
Transforms, Real Variables, Complex Variables, Linear Algebra, Calculus I, II, III, Statistics, Probability,
Operations Research and Linear Programming.
Geophysics courses: Fourier Transforms, Potential Theory, Seismic Processing, Geology and Stratigraphy
