
include::../../../dir/inc/DefPractice.adoc[]

== [.black]#Embrace#

=== [.black]#Psychological Safety#

"A sense of confidence that the team will not embarrass, reject or punish someone for speaking up"

"It describes a team climate characterized by interpersonal
trust and mutual respect in which people are comfortable being themselves."


=== [.black]#Google's Project Aristotle 2012#

* Studied hundreds of teams to figure out why some stumbled while others soared.
* Collect lots of data, but initially they could not see any strong patterns.
* So they wisely stepped back and reframe the initial questions
* They uncovered group norms
* "Concluded that understanding and influencing group norms were the keys to improving Google’s teams"
* ‘‘I’d been on some teams that left me feeling totally exhausted and others where I got so much energy from the group.’’


link::www.nytimes.com/.../what-google-learned-from-its-quest-to-build-the-perfect-team.html[Psychological Safety Ney York Times]

=== [.black]#Positve Team Traits#

Conversational turn-taking::
"As long as everyone got a chance to talk, the team did well."

Average social sensitivity::
Skill at intuiting how others felt based on their tone of voice

Goals and Dependability::
Teams need clear goals and to create a culture of dependability


=== [.black]#Findings#

Purpose::
‘‘We had to get people to establish psychologically safe environments,’’ Rozovsky told me. But it wasn’t clear how to do that. ‘‘People here are really busy,’’ she said. ‘‘We needed clear guidelines.’’

Challenge::
However, establishing psychological safety is, by its very nature, somewhat messy and difficult to implement.
You can tell people to take turns during a conversation and to listen to one another more.
You can instruct employees to be sensitive to how their colleagues feel and to notice when someone seems upset.
But the kinds of people who work at Google are often the ones who became software engineers because they wanted to avoid talking about feelings in the first place.

Norms::
Rozovsky and her colleagues had figured out which norms were most critical.
Now they had to find a way to make communication and empathy — the building blocks of forging real connections — into an algorithm they could easily scale.

Desire::
What Project Aristotle has taught people within Google is that no one wants to put on a ‘‘work face’’ when they get to the office. No one wants to leave part of their personality and inner life at home. But to be fully present at work, to feel ‘‘psychologically safe,’’ we must know that we can be free enough, sometimes, to share the things that scare us without fear of recriminations. We must be able to talk about what is messy or sad, to have hard conversations with colleagues who are driving us crazy. We can’t be focused just on efficiency. Rather, when we start the morning by collaborating with a team of engineers and then send emails to our marketing colleagues and then jump on a conference call, we want to know that those people really hear us. We want to know that work is more than just labor.

Sharing Feelings::
Project Aristotle has encouraged emotional conversations and discussions of norms among people who might otherwise be uncomfortable talking about how they feel. ‘‘Googlers love data,’’ Sakaguchi told me. But it’s not only Google that loves numbers, or Silicon Valley that shies away from emotional conversations. Most work­places do. ‘‘By putting things like empathy and sensitivity into charts and data reports, it makes them easier to talk about,’’ Sakaguchi told me. ‘‘It’s easier to talk about our feelings when we can point to a number.’’

Paradox::
The paradox, of course, is that Google’s intense data collection and number crunching have led it to the same conclusions that good managers have always known. In the best teams, members listen to one another and show sensitivity to feelings and needs

Reminder::
Project Aristotle is a reminder that when companies try to optimize everything, it’s sometimes easy to forget that success is often built on experiences — like emotional interactions and complicated conversations and discussions of who we want to be and how our teammates make us feel — that can’t really be optimized.