
include::../../../dir/inc/DefPractice.adoc[]

==  [.black]#Innovate#

=== [.black]#Principles#
include::Innovate.Prin.adoc[]
<<<

=== [.black]#Product#
include::../2.Product/Preview.adoc[]
<<<

=== [.black]#What Makes Innovate Work#

==== [.black]#Where Our Good Ideas Come From#

[horizontal]
Connection:: Lots of connections as illustrated by the color coded rectangles.
Ecosystem::  The connections alow ideas to flow and interactive in novel ways.
Adjacent::   Interelated tiers represented by hexagons have adjacent sides with meaning.
Hunches::    Everyone is Entitled to evolve their hunches.
Extend::     Special purpose tiers are extended to other purposes.
Convergent:: Propositions converge into the Product Portfolio and Services.
Learning::   We Embrace Change to Adapt to, Discover and Govern new strategies.
Space::      Our Practices provide a comprehensize space for "Good Ideas" to Emerge.

==== [.black]#Improvement#
[horizontal]
Refinement:: Our Products are successively refined by our Learn, Do and Share perspectives
Continuous:: We continously track, Adapt and Deliver new Technology.
Excellence:: We strive for excellence in everything we do. 

==== [.black]#Transparency#
[horizontal]
Share::      We Document, store and Warehouse all of our Information.
Transparent: Our Infomation is always available at Learn, Do and Share perspectives.
Agenda::     Our tactical Adaptations, Changes and strategic Vision are open.




