
include::../../../dir/inc/DefPractice.adoc[]

== [.black]#Innovate#

Both evolution and innovation thrive in collaborative networks where opportunities for serendipitous connections exist. Great discoveries often evolve as slow hunches, maturing and connecting to other ideas over time.

Innovation::
Innovations are a broad category, relative to the current knowledge of the analyzed unit. Any idea, practice, or object that is perceived as new by an individual or other unit of adoption could be considered an innovation available for study.[14]

Adopters::
Adopters are the minimal unit of analysis. In most studies, adopters are individuals, but can also be organizations (businesses, schools, hospitals, etc.), clusters within social networks, or countries.[15]

Communication channels::
Diffusion, by definition, takes place among people or organizations. Communication channels allow the transfer of information from one unit to the other.[16] Communication patterns or capabilities must be established between parties as a minimum for diffusion to occur.[17]

Time::
The passage of time is necessary for innovations to be adopted; they are rarely adopted instantaneously. In fact, in the Ryan and Gross (1943) study on hybrid corn adoption, adoption occurred over more than ten years, and most farmers only dedicated a fraction on their fields to the new corn in the first years after adoption.[6][18]

Social system::
The social system is the combination of external influences (mass media, organizational or governmental mandates) and internal influences (strong and weak social relationships, distance from opinion leaders).[19] There are many roles in a social system, and their combination represents the total influences on a potential adopter.[20]

Studies have explored many characteristics of innovations. Meta-reviews have identified several characteristics that are common among most studies.[21] These are in line with the characteristics that Rogers initially cited in his reviews.[22]

=== [.black]#Characteristics#

Potential adopters evaluate an innovation on its relative advantage (the perceived efficiencies gained by the innovation relative to current tools or procedures), its compatibility with the pre-existing system, its complexity or difficulty to learn, its trialability or testability, its potential for reinvention (using the tool for initially unintended purposes), and its observed effects. These qualities interact and are judged as a whole. For example, an innovation might be extremely complex, reducing its likelihood to be adopted and diffused, but it might be very compatible with a large advantage relative to current tools. Even with this high learning curve, potential adopters might adopt the innovation anyway.[22]

Studies also identify other characteristics of innovations, but these are not as common as the ones that Rogers lists above.[23] The fuzziness of the boundaries of the innovation can impact its adoption. Specifically, innovations with a small core and large periphery are easier to adopt.[24] Innovations that are less risky are easier to adopt as the potential loss from failed integration is lower.[25] Innovations that are disruptive to routine tasks, even when they bring a large relative advantage, might not be adopted because of added instability. Likewise, innovations that make tasks easier are likely to be adopted.[26] Closely related to relative complexity, knowledge requirements are the ability barrier to use presented by the difficulty to use the innovation. Even when there are high knowledge requirements, support from prior adopters or other sources can increase the chances for adoption.[27]

=== [.black]#Decision Levels#

Knowledge:: The individual is first exposed to an innovation, but lacks information about the innovation. During this stage the individual has not yet been inspired to find out more information about the innovation.
Persuasion:: The individual is interested in the innovation and actively seeks related information/details.
Decision:: The individual takes the concept of the change and weighs the advantages/disadvantages of using the innovation and decides whether to adopt or reject the innovation. Due to the individualistic nature of this stage, Rogers notes that it is the most difficult stage on which to acquire empirical evidence.[11]
Implementation:: The individual employs the innovation to a varying degree depending on the situation. During this stage the individual also determines the usefulness of the innovation and may search for further information about it.
Confirmation:: The individual finalizes his/her decision to continue using the innovation. This stage is both intrapersonal (may cause cognitive dissonance) and interpersonal, confirmation the group has made the right decision.
