
include::../../../dir/inc/DefPractice.adoc[]

== [.black]#The Principles Behind Each Column and Practice#



=== [.black]#Embrace#

* Activities have gravitated away from individuals and towards teams.

[horizontal]
Psychological Safety::
* We instill a sense of confidence so that everyones' contributions are sought after and valued.
* Everyone is comfortable being themselves.
* Jobs and lifestyles are in harmonony.
Mutual Respect::
* We respect everyones diversity and are sensitve about their viewpoints.
* We work as a team within our organization, across organizations and with our customers.


[horizontal]
Interpersonal:: Our teams thrive on interpersonal trust.
Committment::   We do not say it unless we mean it. We do what we say we will do, when we say we will do it.
Partnership::   We firmly believe in being a trustworthy partner to everyone.

=== [.black]#Innovate#

Where Good Ideas Come From::

[horizontal]
Ecosystem::  Allows ideas to be diffused and be reconnected in novel ways.
Connection:: Chance favors the connected mind with serendipitous discoveries
Adjacent::   Possibilities emerge and become close waiting to be connected.
Hunches::    Ideas evolve over time as slow hunches rather than sudden breakthroughs.
Repurpose::  Technologies engineered for one purpose are extended to other purposes.
Convergen::  Ideas converge in a shared physical or intellectual space.
Learning::   Leverage change to adopt new strategies.

Improvement:

* We facilitate everyone to be involved in continuously improving our products, technology and delivery.
* We create the space and allocate the resources for long term strategies.
* We strive for excellence in everything we do..  


=== [.black]#Encourage#

Customer Focus:

* We strive to discover ours customer needs to the best of our abilities.
* We recognize our teams and customers are the reason for our existence.

Vision:

* We communicate our positive "Why" message to everyone expecially our customers.
* Everything we do benefits everyone.
* We govern ourselves with vision and passion. 

Assumptions:

[horizontal]
List::       We list, track and challenges all our assumptions
Pivot::      Our mistakes help us abandon our old assumptions

Transparency:

* We share information freely with everyone.
* We are transparent with everything and everyone.
* We have no hidden agendas.


