// Generated by CoffeeScript 1.9.3
(function() {
  var initialize, pdfCSS;

  $(document).ready(function() {
    initialize();
    pdfCSS();
  });

  initialize = function() {
    var bower, revdir;
    bower = '../../lib/bower_components/';
    revdir = bower + 'reveal.js/';
    Reveal.initialize({
      controls: true,
      progress: true,
      history: true,
      center: true,
      slideNumber: true,
      transition: 'slide',
      math: {
        mathjax: bower + 'MathJax/MathJax.js',
        config: 'TeX-AMS_HTML-full'
      },
      dependencies: [
        {
          src: revdir + 'lib/js/classList.js',
          condition: function() {
            return !document.body.classList;
          }
        }, {
          src: revdir + 'plugin/markdown/marked.js',
          condition: function() {
            return !!document.querySelector('[data-markdown]');
          }
        }, {
          src: revdir + 'plugin/markdown/markdown.js',
          condition: function() {
            return !!document.querySelector('[data-markdown]');
          }
        }, {
          src: revdir + 'plugin/highlight/highlight.js',
          async: true,
          condition: function() {
            return !!document.querySelector('pre code')({
              callback: function() {
                return hljs.initHighlightingOnLoad();
              }
            });
          }
        }, {
          src: revdir + 'plugin/zoom-js/zoom.js',
          async: true
        }, {
          src: revdir + 'plugin/math/math.js',
          async: true
        }
      ]
    });
  };

  pdfCSS = function() {
    var bower, link, revdir;
    bower = '../../lib/bower_components/';
    revdir = bower + 'reveal.js/';
    link = document.createElement('link');
    link.rel = 'stylesheet';
    link.type = 'text/css';
    link.href = window.location.search.match(/print-pdf/gi) ? revdir + 'css/print/pdf.css' : revdir + 'css/print/paper.css';
    document.getElementsByTagName('head')[0].appendChild(link);
  };

}).call(this);
