
include::../../../dir/inc/DefPractice.adoc[]

==== [.black]#Psychological Safety#
Confidence in ones expertise and ones Identity are cultivated within an Expert Team.
Everyone is comfortable with their core Expertise and Product Contributions which are
kept in Safely in Harmony by direct representation.

[horizontal]
Confidence::   Our teams instill confidence into each member.
Contribution:: Everyone's individual contributions are sought after and valued.
Identity::     Everyone is comfortable being themselves.
Harmonony::    Jobs and lifestyles are kept in balance.
Safety::       We will not embarrass, reject or punish someone for speaking up.

==== [.black]#Mutual Respect#
Our teams are Diverse like our Products that Include everyone's viewpoints.
We make work Together and Individually on Products

[horizontal]
Diversity::  We recognize everyone's diversity and approach.
Individual:: We include in everyone's individual viewpoints.
Together::   Together we make work happen.

==== [.black]#Trust#
Our Charter communicates who we are to us and our community.
We Commit to the work vy responding to requests daily, we maintain the trust of out community and Partners.

[horizontal]
Interpersonal:: Our teams thrive on interpersonal trust.
Commitment::    We do not say it unless we mean it. We say we will do .
Partner::       We are a trustworthy partner to everyone.

