
include::../../../../dir/inc/DefStudy.adoc[]

''''
<<<<
=== [.black]#Logistic Regression#

include::Logistic.Slide.adoc[]

==== [.black]#How It Works#

* In statistics, logistic regression is a regression model where the dependent variable (DV) is categorical.
* The binary logistic model is used to estimate the probability of a binary response based on one or more predictor (or independent) variables (features).

* Measures the relationship between the categorical dependent variable and one or more independent variables by estimating probabilities using a logistic function

==== [.black]#Analogous to Linear#

* A special case of the generalized linear model and thus analogous to linear regression.
* The model of logistic regression, however, is based on quite different assumptions
  (about the relationship between dependent and independent variables) from those of linear regression.
* In particular the key differences of these two models can be seen in the following two features of logistic regression.
* First, the conditional distribution is a Bernoulli distribution rather than a Gaussian distribution
  because the dependent variable is binary.
* Second, the predicted values are probabilities and are therefore restricted to (0,1)
  through the logistic distribution function because logistic regression predicts the probability of particular outcomes.



