

include::../../../../dir/inc/DefStudy.adoc[]

''''
<<<<
=== [.black]#Nearest Neighbor#
include::NearestNeighbor.Slide.adoc[]

==== [.black]#How It Works#
* The output depends on whether k-NN is used for classification or regression:
  ** In k-NN classification, the output is a class membership. An object is classified by a majority vote of its neighbors, with the object being assigned to the class most common among its k nearest neighbors (k is a positive integer, typically small). If k = 1, then the object is simply assigned to the class of that single nearest neighbor.

  ** In k-NN regression, the output is the property value for the object. This value is the average of the values of its k nearest neighbors.

* k-NN is a type of instance-based learning, or lazy learning, where the function is only approximated locally and all computation is deferred until classification. The k-NN algorithm is among the simplest of all machine learning algorithms.

* Both for classification and regression, it can be useful to assign weight to the contributions of the neighbors, so that the nearer neighbors contribute more to the average than the more distant ones. For example, a common weighting scheme consists in giving each neighbor a weight of 1/d, where d is the distance to the neighbor.[2]

* The neighbors are taken from a set of objects for which the class (for k-NN classification) or the object property value (for k-NN regression) is known. This can be thought of as the training set for the algorithm, though no explicit training step is required.

////
==== [.black]#Benefits#
* One
* Two

==== [.black]#Drawbacks#
* Sensitivity to the local structure of the data.
* Two

==== [.black]#When To Use It#
* One
* Two

==== [.black]#Getting Started#
* One
* Two

==== [.black]#Proving Results#
* One
* Two

==== [.black]#Applications#
* One
* Two

==== [.black]#Tools#
[horizontal]
Spark:: xxx
Python:: xxx
R:: xxx
////