
=== [.black]#Story#

==== [.black]#Background#

 It may be because
I grew up in a beautiful house enveloped in an oak forest where I built
a log cabin or treehouse, or that my mother me and my brothers and sister
to the library twice a week, or that each of us had our own train
and chemistry sets, or that I could walk outside and play football and
baseball with my neighborhood friends, or that I could walk three blocks to
our neighborhood pool club to swim all summer, or that my Boy Scout Troop
would take us camping every month, or that my father was a talented
aerospace engineer who brilliantly shared the joy of his work, or that my
mother was a hard working caretaker who made life easy for us all, or that I
had to honor of going to the best high school Calvert Hall from 1967 to 1971
and was wonderfully stimulated by the 60's or that I could take the bus downtown
to the Peabody Institue to learned to play the piano, then afterwoods head
over to Mount Vernon Park to experience Baltimore Summer of Love and then
form a psychelic rock band with my childhood friends, or that math was
easy for me in class so that Calvert Hall gave me a desk in the study hall
to tutor other students. or that my high school physchology teacher showed
me Maslow's what Self Actuallization meant, or that Brother Henry staged a
happening in our High School auditorium.

Who knows, but what I do know that the world is a multifaceted place full
of wonder and I now fully appreciate my wonderful parents, teachers and
neighbors who worked hard to let it all happen.

==== [.black]#Challenge#

I personally have always felt that Innovation is easy.

